trigger:
  batch: true
  branches:
    include:
    - main
    exclude:
    - request/*

pr: none

resources:
  repositories:
  - repository: self

variables:
- group: MY-SECRETS
- name: APP_NAME

stages:
- stage: UpdatePipelines
  displayName: Update Pipelines
  jobs:
  - job: UpdatePipelines
    displayName: Update Pipelines
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      name: processYaml
      env:
        AZURE_DEVOPS_EXT_GITHUB_PAT: $(AZURE_DEVOPS_EXT_GITHUB_PAT)
      inputs:
        targetType: 'inline'
        script: |
          ls -lrt
          ./setup-az-pipelines.sh  


