parameters:

trigger:
  batch: true
  branches:
    include:
    - main
    exclude:
    - request/*

pr: none

resources:
  repositories:
  - repository: self

variables:
- group: MY-SECRETS
- name: APP_NAME

stages:
- stage: Update Pipelines
  displayName: Update Pipelines
  jobs:
  - job: BuildFeature
    displayName: Create Pipelines
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      name: process_yaml
      inputs:
        targetType: 'inline'
        script: |
          ls -lrt
          curl -L -o ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq
          chmod +x ./yq
          PIPE_JSON=$(./yq -o=json  ./pipelines.yml)

          for row in $(echo "${PIPE_JSON}" | jq -r '.[] | @base64'); do
              _jq() {
                echo ${row} | base64 --decode | jq -r ${1}
              }
             _PIPE_NAME=$(echo $(_jq '.name'))
             _AZ_PROJECT=$(echo $(_jq '.az_project'))
             echo "processing Project: $_AZ_PROJECT, Pipeline: $_PIPE_NAME"
          done


